### ISSUE TITLE
Specify YAML Xanadoc format

### ISSUE THREAD

**Issue by ghost** [jakobib/hypertext2019#5]
Hi everyone.

I read your paper and found the points raised interesting, a doubt I have would be... to use yaml to serialize xanadoc data. 

*So... I would like to know what you all think of the yaml data serialization format. 1) Is yaml similar to xanadoc proposal? 2) Is this project active? 3) is it kept?*

#### 1. concept
**1.1 sample 1: hyperland_xuCambDemo1.yaml**
```yaml
# key-value
http: '//hyperland.com/xuCambDemo/WelcXu-D1y,start=25,length=567'
```

**1.2 sample 2: hyperland_xuCambDemo2.yaml**
```yaml
# key-value
http: '//hyperland.com/xuCambDemo/WelcXu-D1y,'
start: '25'
length: '567'
```

#### 2. Idea
**2.1 symbol**
```yaml
# key-value
# protocol or url: http|https|sft|ftp|ssh
protocol: address
```

*What do you all think about this... use case?*
